[package]
name = "bbs-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
bls12_381 = { version = "0.8.0", features = ["groups", "experimental", ] }
sha2 = "0.9.9"
sha3 = "0.9.1"
hex = "0.4.3"
digest = "0.9.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
ff = "0.13.0"